### ISSUE TITLE
Chell Model is visible in first person

### ISSUE THREAD

**Issue by NeverDesk** [Krzyhau/KrzyMod#12]
GTA II effect was active when the mod attempted to load a quicksave. There was no previous quicksave, so the game crashed. When opening the game again, Chell's model was now visible in first person.

**Comment by NeverDesk** [comment]
cl_skip_player_render_in_main_view 1 to fix issue.

**Comment by Krzyhau** [comment]
The game shouldn't crash if there's no quicksave, it should just fail to do anything and continue, so there was definitely something else going on, probably a rare anomaly. As for the viewmodel, the cvar you've mentioned is modified by the GTA II modifier, but there's nothing to set it back in case when the game crashes. Controlled cvars are now prevented from being saved by https://github.com/Krzyhau/KrzyMod/commit/db6645c2609d679aa63eb5220a759216769f7f30, preventing this issue. I'm keeping it closed.
