### ISSUE TITLE
How did you develop this?

### ISSUE THREAD

**Issue by karl-police** [Krzyhau/KrzyMod#13]
How did you develop this?

Like, not sure.

But I don't think there's a documentation or something for Portal 2 or how to create plugins for Portal 2.

How did you create it?

**Comment by misleadingname** [comment]
It is called OSS for a reason :eyes:

**Comment by karl-police** [comment]
> It is called OSS for a reason 👀

Yeah, but I don't understand everything. Like, does Portal 2 have a thing that let's people create stuff like that, or is it like an injector?

**Comment by Krzyhau** [comment]
Source Engine has a [built-in support for server plugins](https://developer.valvesoftware.com/wiki/Server_plugins), which allows you to load the plugin in the game without injecting it using `plugin_load` command, and also exposes several functions for you to work with. However, that's not nearly enough, so we supplement these with structures, references and hooks that we've either figured out from the source code of publicly available Source Engine branches or just reverse-engineering.

The plugin was heavily based on [SourceAutoRecord](https://github.com/p2sr/SourceAutoRecord/). I recommend looking at its source code to see more examples of the crazy stuff that makes everything works.
